# Generated by Django 3.2.12 on 2022-02-22 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ModelApp', '0001_add_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 13, 35, 42, 292685, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='person',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 13, 35, 42, 292718, tzinfo=utc)),
        ),
    ]
